before_script:
    - apt-get -qq update
    - apt-get install -y build-essential g++-4.8

node08:
    script:
    - rm -rf $CI_PROJECT_DIR/.nvm && git clone https://github.com/creationix/nvm.git $CI_PROJECT_DIR/.nvm && (cd $CI_PROJECT_DIR/.nvm && git checkout `git describe --abbrev=0 --tags`) && source $CI_PROJECT_DIR/.nvm/nvm.sh && nvm install v0.8 && nvm use v0.8
    - npm install npm@2 && node_modules/.bin/npm install npm
    - mv node_modules npm
    - npm/.bin/npm --version
    - export CXX=g++-4.8
    - $CXX --version
    - npm/.bin/npm install --unsafe-perm

node10:
    script:
    - rm -rf $CI_PROJECT_DIR/.nvm && git clone https://github.com/creationix/nvm.git $CI_PROJECT_DIR/.nvm && (cd $CI_PROJECT_DIR/.nvm && git checkout `git describe --abbrev=0 --tags`) && source $CI_PROJECT_DIR/.nvm/nvm.sh && nvm install v0.10 && nvm use v0.10
    - npm install npm
    - mv node_modules npm
    - npm/.bin/npm --version
    - export CXX=g++-4.8
    - $CXX --version
    - npm/.bin/npm install --unsafe-perm

node12:
    script:
    - rm -rf $CI_PROJECT_DIR/.nvm && git clone https://github.com/creationix/nvm.git $CI_PROJECT_DIR/.nvm && (cd $CI_PROJECT_DIR/.nvm && git checkout `git describe --abbrev=0 --tags`) && source $CI_PROJECT_DIR/.nvm/nvm.sh && nvm install v0.12 && nvm use v0.12
    - npm install npm
    - mv node_modules npm
    - npm/.bin/npm --version
    - export CXX=g++-4.8
    - $CXX --version
    - npm/.bin/npm install --unsafe-perm

node4:
    script:
    - rm -rf $CI_PROJECT_DIR/.nvm && git clone https://github.com/creationix/nvm.git $CI_PROJECT_DIR/.nvm && (cd $CI_PROJECT_DIR/.nvm && git checkout `git describe --abbrev=0 --tags`) && source $CI_PROJECT_DIR/.nvm/nvm.sh && nvm install v4 && nvm use v4
    - npm install npm
    - mv node_modules npm
    - npm/.bin/npm --version
    - export CXX=g++-4.8
    - $CXX --version
    - npm/.bin/npm install --unsafe-perm

node5:
    script:
    - rm -rf $CI_PROJECT_DIR/.nvm && git clone https://github.com/creationix/nvm.git $CI_PROJECT_DIR/.nvm && (cd $CI_PROJECT_DIR/.nvm && git checkout `git describe --abbrev=0 --tags`) && source $CI_PROJECT_DIR/.nvm/nvm.sh && nvm install v5 && nvm use v5
    - npm install npm
    - mv node_modules npm
    - npm/.bin/npm --version
    - export CXX=g++-4.8
    - $CXX --version
    - npm/.bin/npm install --unsafe-perm

node6:
    script:
    - rm -rf $CI_PROJECT_DIR/.nvm && git clone https://github.com/creationix/nvm.git $CI_PROJECT_DIR/.nvm && (cd $CI_PROJECT_DIR/.nvm && git checkout `git describe --abbrev=0 --tags`) && source $CI_PROJECT_DIR/.nvm/nvm.sh && nvm install v6 && nvm use v6
    - npm install npm
    - mv node_modules npm
    - npm/.bin/npm --version
    - export CXX=g++-4.8
    - $CXX --version
    - npm/.bin/npm install --unsafe-perm
